### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by GLC-Delivers** [afragen/embed-pdf-viewer#11]
Our company is increasingly concerned with  accessiblity for people with sight, hearing and mobility issues. I was wondering if there was any way you could add a menu item called "Long Description" that would allow us to paste a text only description of the pdf we are embedding. That would be SO COOL.

**Comment by afragen** [comment]
I'll have to look into this. I'm not sure how easy/hard it will be.

**Comment by afragen** [comment]
In the latest `develop` branch I've added the media object description as a `title` tag. If you fill out the description in the Media Library, it will be used.

I hope that works.

**Comment by afragen** [comment]
I’m adding a Description metabox in the block that can be used to add a content to a title tag. 

If there’s something else needed for accessibility let me know.

**Comment by GLC-Delivers** [comment]
Thanks!

________________________________

**Comment by GLC-Delivers** [comment]
Sorry I was on vacation last week.

________________________________
