### ISSUE TITLE
Firefox and mobile browsers not displaying embedded PDF

### ISSUE THREAD

**Issue by ianbelanger79** [afragen/embed-pdf-viewer#15]
I am using you plugin and have found that the embedded iframe is not displaying on Firefox desktop, nor any mobile browsers. It works great on Chrome and Edge desktop.

**Comment by afragen** [comment]
I have checked a PDF embed on Firefox and it seems to work as expected for me.

**Comment by ianbelanger79** [comment]
This is the url https://blogs.sw.siemens.com/electronics-semiconductors/2024/04/16/toward-a-people-centric-and-adaptive-production-ecosystem/ the embedded PDF is near the bottom of the post

**Comment by afragen** [comment]
This PDF shows up for me in Firefox.

<img width="955" alt="screenshot_567" src="https://github.com/afragen/embed-pdf-viewer/assets/1296790/5a28ff3b-bdbb-4eb8-b592-c43d51b3897f">
