### ISSUE TITLE
Adjust frame size

### ISSUE THREAD

**Issue by Go-rom** [afragen/embed-pdf-viewer#3]
Hello

First, thank you very much for this useful plugin.

I just would like to know if there a way to modify the frame size that contains the embed pdf.

Thank you !

**Comment by afragen** [comment]
The frame size is somewhat dependent upon the the size of the PDF. When I set it up I tried for a size that seemed most versatile. 

The size settings are in https://github.com/afragen/embed-pdf-viewer/blob/699538101918a1ce80bc84479086d066cf1495dd/embed-pdf-viewer.php#L109-L128

If you find something better or need a filter to be able to set your own values, let me know.

**Comment by Go-rom** [comment]
Ok i've spotted these values in the php file : 500px and 800px.
But when i look into the source code of my webpage, i find these values : 500px (height) and 680px (width)

However, i did edit the values into the php file with 1000px and 800px but i'm still stuck with 500px and 680px.

Maybe i have to clear a cache storage or something like that ?

Thank you

**Comment by afragen** [comment]
If there are values in the file these are used preferentially to the defaults.

**Comment by afragen** [comment]
@Go-rom in the develop branch I've added a filter to change the PDF attributes. This is a global filter and does not work on a PDF by PDF basis.

```php
add_filter( 'embed_pdf_viewer_pdf_attributes', function($attr) {
    $attr['height'] = <my_height>;
    $attr['width'] = <my_width>;

    return $attr;
});
```

LMK if that helps.

**Comment by NoobyNoob1966** [comment]
It works but the function adds "px" to the end of attribute so if I add "500px" in new filter hook it would return 500pxpx on the page.
So in the hook dimensions need to be without px.

I was trying to add "100%" width so it would scale on different screens but this makes it not possible.

Possible workaround?

Thanks.

**Comment by afragen** [comment]
I can adjust the code. I didn’t anticipate using something other than px. 

I’ll have to make sure there’s a default type as well.

**Comment by afragen** [comment]
This may be difficult as the fallback is for the iframe, which specifically writes ‘px’ in the code. However, the object tag only has a number and it uses pixel for the unit of that number. 

Given that, I’m not sure there’s a way to accommodate. Sorry.
