### ISSUE TITLE
Block editor save results in validation error after changing attributes

### ISSUE THREAD

**Issue by afragen** [afragen/embed-pdf-viewer#6]
@akirk It seems that adjusting the blocks frame size causes the block editor to add a surrounding `<figure>` tag to the `iframe` that contains the changed height or width. In this was only in the `iframe`.

This causes an invalid content error when trying to edit the post again.

![screenshot_01](https://user-images.githubusercontent.com/1296790/50057359-28ffa500-011e-11e9-9be4-b2ca0164708c.png)

![screenshot_04](https://user-images.githubusercontent.com/1296790/50057701-d4125d80-0122-11e9-8ae3-df6d61c4d036.png)

Any ideas on how to fix this?

**Comment by afragen** [comment]
I think this is related. https://github.com/WordPress/gutenberg/issues/10444

**Comment by afragen** [comment]
Interesting. Even removing the `iframe` (which I can't do) causes the same resolve error but there is no difference that I can see. Seems like an error in validation.

![screenshot_05](https://user-images.githubusercontent.com/1296790/50058245-6407d580-012a-11e9-9c99-33e95c97bf37.png)

**Comment by afragen** [comment]
The console log in Firefox is showing the Block validation error as expecting to see the default height/width but actually seeing the changed height/width.

**Comment by afragen** [comment]
I did a bunch more digging, at least as much as I could. 

It seems that in the `renderEdit` `attr` is correctly saving all the data. I don't know what _Update_ does with that data.

The issue seems to be in `renderEmbed` that none of the saved attributes are brought into that function. This means that `renderEdit` only ever _sees_ default data.

The `align` seems to save and it passed to `renderEmbed`

When `renderEdit` calls `renderEmbed` all the parameters are passed. When `renderEmbed` is called outside of `renderEdit` only the default parameters and `align` are passed.

I hope some of this makes sense.

**Comment by akirk** [comment]
Happy to take a look in the course of the week, aligning the generated HTML with the loading can be tricky. Thanks for the details, that helps me understand what you've already tried.

**Comment by afragen** [comment]
I think this is related. https://github.com/WordPress/gutenberg/issues/7016

**Comment by afragen** [comment]
Perhaps this change. I haven’t tested.

https://github.com/afragen/embed-pdf-viewer/blob/01771388bcb88bfd2abf52398ac4464cf262300d/blocks/index.js#L57

to

`setAttributes( { key: key.value } );` or `setAttributes( { key: value } );`

This because setting a PDF from a media item saves. Just brainstorming.

**Comment by afragen** [comment]
So the issue seemed to be that an attribute of type `number` was not being stored but when changing to type `string` it was being stored. Both `width` and `height` were of type `number`, now they are working as type `string`   🤷‍♂️
